version: '2.0'
services:
  mysql:
    image: mysql:5.7
    container_name: itom_project_mysql
    restart: always
    ports:
      - "33062:3306"
    volumes:
      - ./docker_files/mysql/data:/var/lib/mysql
      - ./docker_files/mysql/conf:/etc/mysql/conf.d
      - ./docker_files/mysql/logs:/var/log/mysql
      - ./docker_files/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=pwd123456
      - TZ=Asia/Shanghai
    command: ['mysqld']
    networks:
      - net-itom_project

  backend:
    image: tyhub.touch4.me/ops/itom_project:1.0.0
    container_name: itom_project
    restart: always
    working_dir: /data/server/itom_project
    env_file:
      - .env
    ports:
      - "7000:8000"
    volumes:
      -  /data/server/itom_project/static #静态文件
      - ./itom_project:/data/server/itom_project  #代码
      - ./itom_project/logs:/data/server/itom_project/logs  #日志
    depends_on:
      - mysql
    networks:
      - net-itom_project
    command: ['sh', '/data/server/run/wait-for.sh', 'mysql:3306', '--', 'sh', '/data/server/run/start.sh']

  nginx:
    image: tyhub.touch4.me/ops/tyops-nginx:0.0.1
    container_name: itom_project_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "7001:80"
    volumes:
      - ./docker_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./itom_project/logs:/var/log/nginx/
      - /data/itom-project-vue/dist:/data/dist
    volumes_from:
      - backend
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-itom_project


networks:
  net-itom_project: